dist: bionic
addons:
  chrome: stable
language: python
sudo: required
python:
    - "3.6"

before_script:
    - sleep 10

before_install:
    - "curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.2.0-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.2.0-amd64.deb"
    - sudo sed -i.old 's/-Xms1g/-Xms128m/' /etc/elasticsearch/jvm.options
    - sudo sed -i.old 's/-Xmx1g/-Xmx128m/' /etc/elasticsearch/jvm.options
    - echo -e '-XX:+DisableExplicitGC\n-Djdk.io.permissionsUseCanonicalPath=true\n-Dlog4j.skipJansi=true\n-server\n' | sudo tee -a /etc/elasticsearch/jvm.options
    - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
    - "sudo service elasticsearch start"
    - "wget https://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_linux64.zip; unzip chromedriver_linux64.zip -d chromedriver; export PATH=$PATH:`pwd`/chromedriver"

install: 
    - "pip install -r requirements_dev.txt"

script:
    - "flake8 ."
    - "ALLOWED_HOSTS=localhost py.test"

