version: "3.5"

services:

  grantnav-test:
    build: .
    ports:
      - "8000:8000"
    environment:
      ALLOWED_HOSTS: 'localhost'
      DEBUG: 'True'
      ELASTICSEARCH_HOST: 'elasticsearch-test'
      PROVENANCE_JSON: "/code/datastoredata/data/data_all.json"
    volumes:
      - "./:/code"
    command: "su -c 'chmod a+x docker-compose.test.sh && ./docker-compose.test.sh'"
    depends_on:
      - elasticsearch-test

  elasticsearch-test:
    image: elasticsearch:7.12.1
    environment:
      "discovery.type": 'single-node'
      "search.max_buckets": "200000"
      "TAKE_FILE_OWNERSHIP": "True"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "./elasticsearch_test_data:/usr/share/elasticsearch/data/"

