version: "3.5"

services:

  grantnav-test:
      build: .
      tty: true
      environment:
        ALLOWED_HOSTS: 'localhost'
        DEBUG: 'True'
        PYTHONUNBUFFERED: 1
        ELASTICSEARCH_HOST: 'elasticsearch'
      volumes:
        - "./:/grantnav"
      depends_on:
        - elasticsearch

  elasticsearch:
    image: elasticsearch:7.17.23
    environment:
      "discovery.type": 'single-node'
      "TAKE_FILE_OWNERSHIP": "True"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data/"
 
volumes:
   elasticsearch_data: {}