name: Compile CSS
on: [push, pull_request]

jobs:
  compilecss:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
        architecture: x64
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_dev.txt') }}
    - run: pip install -r requirements.txt
    - run: pip install -r requirements_dev.txt
    - run: pysassc grantnav/frontend/sass/main.scss grantnav/frontend/static/css/theme-compiled.css
    - run: diff grantnav/frontend/static/css/theme.css grantnav/frontend/static/css/theme-compiled.css
